spring.application.name=gamehub

# Conexion local a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gamehub
spring.datasource.username=gamehub_app
spring.datasource.password=${DB_PASSWORD}

# Durante esta etapa, Hibernate solo valida el esquema existente.
spring.jpa.hibernate.ddl-auto=validate

# Steam Web API
steam.api.base-url=https://api.steampowered.com
steam.api.key=${STEAM_API_KEY:}
