spring.application.name=gamehub

# Conexion local a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gamehub
spring.datasource.username=gamehub_app
spring.datasource.password=${DB_PASSWORD}

# Durante esta etapa, Hibernate solo valida el esquema existente.
spring.jpa.hibernate.ddl-auto=validate

# Steam Web API
steam.api.base-url=https://api.steampowered.com
steam.api.key=${STEAM_API_KEY:}

# RAWG Video Games Database API
rawg.api.base-url=https://api.rawg.io/api
rawg.api.key=${RAWG_API_KEY:}

igdb.api.base-url=https://api.igdb.com/v4
igdb.auth.base-url=https://id.twitch.tv
igdb.client-id=${IGDB_CLIENT_ID:}
igdb.client-secret=${IGDB_CLIENT_SECRET:}
